name: CI for film svc

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  film-svc:
    name: Build and Test on Python 3.12
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest app/tests